server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://USER
          predicates:
            - Path=/api/auth/**

        - id: user
          uri: lb://USER
          predicates:
            - Path=/api/users/**
          filters:
            - name: RoleAuth
              args:
                roles: [ ADMIN ]

        - id: service1
          uri: lb://SERVICE1
          predicates:
            - Path=/api/service1/**
          filters:
            - name: RoleAuth
              args:
                roles: [ ADMIN, MODERATOR ]

        - id: service2
          uri: lb://SERVICE2
          predicates:
            - Path=/api/service2/**
          filters:
            - name: RoleAuth
              args:
                roles: [ USER ]