server:
  port: 8083

spring:
  application:
    name: service-2
  datasource:
    url: jdbc:mysql://localhost:3306/service2?&createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
